### ISSUE TITLE
Generate ICC profiles

### ISSUE THREAD

**Issue by Mart-Bogdan** [bruvellu/color-blind-luts#1]
Is it possible to generate icc from this lut files?

**Comment by bruvellu** [comment]
Sorry, I'm not familiar with ICC profiles. I imagine it is possible...

**Comment by Mart-Bogdan** [comment]
I understand. I'll try researching it.

This could allow colorblind people set custom profiles on their computers, to better observe WEB.

If I understand correctly, this LUTs allow to convert images, so they can be perceived  by colorblind people?

**Comment by bruvellu** [comment]
Yes, I load these LUTs on microscopy images using Fiji/ImageJ.
