### ISSUE TITLE
File type does not seem to be supported by modern photoshop.

### ISSUE THREAD

**Issue by Artellia** [bruvellu/color-blind-luts#2]
File type does not seem to be supported by modern photoshop.
Adding a color adjustment layer requests a 3dlut in one of various formats. one format I might be able to select is a .1dls which I'm guessing is a 1dlut file, but still a different format from these. can you convert your lut files to something more easily used?

**Comment by bruvellu** [comment]
Hi, the LUTs were made for Fiji/ImageJ. Perhaps there's a way to convert, but I'm not aware of it.
